steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - '-c'
      - gcloud app deploy --project $PROJECT_ID
    entrypoint: bash
timeout: 1600s
options:
  logging: CLOUD_LOGGING_ONLY